### ISSUE TITLE
External build is broken due to wmass benchmark

### ISSUE THREAD

**Issue by stwunsch** [root-project/rootbench#167]
I get following error with an external build

```
input_line_12:3:10: fatal error: 'inc/classes.h' file not found
#include "inc/classes.h"
         ^~~~~~~~~~~~~~~
Error: /home/stefan/builds/root-dev/bin/rootcling: compilation failure (/home/stefan/builds/rootbench/root/tree/dataframe/wmass/libSignalAnalysis522503ca6b_dictUmbrella.h)
make[2]: *** [root/tree/dataframe/wmass/CMakeFiles/G__SignalAnalysis.dir/build.make:85: root/tree/dataframe/wmass/G__SignalAnalysis.cxx] Error 1
make[1]: *** [CMakeFiles/Makefile2:2011: root/tree/dataframe/wmass/CMakeFiles/G__SignalAnalysis.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

which seems to stem from the following dictionary

```
ROOT_GENERATE_DICTIONARY(G__SignalAnalysis inc/classes.h LINKDEF LinkDef.h)
```

**Comment by eguiraud** [comment]
I just recompiled ROOT master (with CMAKE_CXX_STANDARD=17 but standard cmake options otherwise) and then recompiled rootbench from scratch:

```
source ../someroot/bin/thisroot.sh && rm -i -rf * && cmake -Drootbench-datafiles=ON ../rootbench && cmake --build . -- -j8 && ctest -V -R "wmass"
```

It ran fine, so I need help debugging what's failing for you. What's a list of commands that reproduces the problem for you?

**Comment by stwunsch** [comment]
My root is on commit `be0dea9db4814810c14e20c6f2b22e124d4c82d1` (from 2020 Jul 14), and is build with

```
/usr/bin/cmake -DCMAKE_CXX_STANDARD="17" -DCMAKE_CXX_COMPILER="g++" -DCMAKE_C_COMPILER="gcc" -Dccache="ON" -Ddistcc="OFF" -Dtesting="ON" /path/to/root
```

rootbench itself is just build with the root sourced and then ran

```
cmake -Drootbench-datafiles=ON /path/to/rootbench
```

**Comment by stwunsch** [comment]
Seems compatible to your build? Let me update my root to current master and I'll retry

**Comment by stwunsch** [comment]
Alrighty, works with current master. Hard to tell whether it was before just a misconfiguration on my side.
