### ISSUE TITLE
Run only benchmarks in the nightlies?

### ISSUE THREAD

**Issue by stwunsch** [root-project/rootbench#168]
We run all tests, not only the benchmarks, in the rootbench nightlies. Shouldn't we just run the rootbench stuff?

**Comment by oshadura** [comment]
@stwunsch @eguiraud it is a good question,should we will leave only rootbench benchmarks? (sometimes I was catching some failures from root that was not visible in nightlies)

**Comment by eguiraud** [comment]
I don't have an opinion, sorry :)

**Comment by stwunsch** [comment]
I think rootbench should do benchmarks and root/roottest should do tests. Clear separation of concerns :) And we don't get spurious failures in rootbench just because someone put a bug into root master, which does not affect the benchmarks at all.

**Comment by stwunsch** [comment]
Let me pull in @Axel-Naumann, in case he has a strong opinion!

**Comment by oshadura** [comment]
FYI I realized I have clang HEAD builds only in rootbench :)

**Comment by vgvassilev** [comment]
If we tests fail on that platform the Data from benchmarks is very likely irrelevant.

**Comment by stwunsch** [comment]
fair point, so we keep the tests!
