### ISSUE TITLE
Port fixes in opendata-benchmarks to rootbench

### ISSUE THREAD

**Issue by stwunsch** [root-project/rootbench#224]
The fixes from this PRs should be ported here:
https://github.com/root-project/opendata-benchmarks/pull/11
https://github.com/root-project/opendata-benchmarks/pull/12

Note that we have to reskim the original sample, this time removing the `MET_sumet` branch but adding `MET_pt` and `MET_phi`.

**Comment by stwunsch** [comment]
I've linked both PR above! I'll try to take care in the next weeks :) Performance wise, the changes should make no big difference. So porting them back is just for correctness of the code base.

**Comment by eguiraud** [comment]
@ikabadzhov can you please make sure the patches mentioned above are now included? it might very well already be the case

**Comment by ikabadzhov** [comment]
> @ikabadzhov can you please make sure the patches mentioned above are now included? it might very well already be the case

Yes! Changes are applied, and that was indeed the reason why we needed to update the input files to update the branches.

**Comment by eguiraud** [comment]
Great, closing then.
